# Site settings
title:          Trung Nguyen - Design Engineer
description:    "Trung Nguyen - Product Designer, Product Management, User Experience, User Interface, Software Engineer"


# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
